// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf0T6I_g8HfU3jnjMLVD5rdzpUH_lrLzw',
    appId: '1:522505857995:web:b9b06c69950e044d1ce44e',
    messagingSenderId: '522505857995',
    projectId: 'my-project-6bd01',
    authDomain: 'my-project-6bd01.firebaseapp.com',
    storageBucket: 'my-project-6bd01.appspot.com',
    measurementId: 'G-3LV7GFNJET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo1qz9dloQmTpqFFtcwx6huqTGy0aUfXc',
    appId: '1:522505857995:android:51b333eed70476d61ce44e',
    messagingSenderId: '522505857995',
    projectId: 'my-project-6bd01',
    storageBucket: 'my-project-6bd01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTM1ZElSBjOgfr6elm-QYARmg0XVNL55U',
    appId: '1:522505857995:ios:a5cb722da73f607a1ce44e',
    messagingSenderId: '522505857995',
    projectId: 'my-project-6bd01',
    storageBucket: 'my-project-6bd01.appspot.com',
    iosClientId: '522505857995-quh3vvqjdumlfj7c99fs73tqpvo7qgt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTM1ZElSBjOgfr6elm-QYARmg0XVNL55U',
    appId: '1:522505857995:ios:a5cb722da73f607a1ce44e',
    messagingSenderId: '522505857995',
    projectId: 'my-project-6bd01',
    storageBucket: 'my-project-6bd01.appspot.com',
    iosClientId: '522505857995-quh3vvqjdumlfj7c99fs73tqpvo7qgt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginform',
  );
}
